# Generated by Django 5.2 on 2025-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expenses',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
